name: Build Sembako Bot
on:
  push:
    branches:
      - "main"
jobs:
  Main:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v3
      - name: Install Mypy and Pycodestyle
        run: 'pip install mypy pycodestyle'
      - name: Install dependencies
        run: 'pip install -r requirements.txt'
      - name: Run Mypy and Pycodestyle
        run: 'mypy main.py && pycodestyle main.py'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
      - name: Set up cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Configure Docker
        run: 'gcloud auth configure-docker asia.gcr.io -q'
      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: asia.gcr.io/scheduled-chat-bot/sembako-bot:latest
      - name: See SHA256 digest
        run: 'echo ${{ steps.build-and-push.outputs.digest }}'
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '<1.2.0'
      - name: Initialize Terraform
        run: 'terraform init'
      - name: Apply Terraform
        run: "terraform apply -auto-approve -var 'api_key=${{ secrets.TELEGRAM_API_KEY }}' -var 'db_string=${{ secrets.DB_STRING }}' -var 'docker_image=asia.gcr.io/scheduled-chat-bot/sembako-bot@${{ steps.build-and-push.outputs.digest }}' -replace=google_cloud_run_service.sembako"
